### ISSUE TITLE
Getting started is impossible to view in Android Chrome

### ISSUE THREAD

**Issue by grodin** [haskell-servant/haskell-servant.github.io#3]
I'm 99% certain this is due to use of slidy. 

Firstly, vertical scrolling is essentially completely broken. Scrolling down by touch brings up the menu and scrolling up just doesn't happen.

Secondly, whenever there is a wide element like a code snippet which causes horizontal scrolling to be enabled, page flipping by swipe doesn't work either.

Like I said, this is basically slidy, and I couldn't find an issue tracker for that so I'm raising it here so you know about it.

On the positive side, what I've been able to understand about Servant looks really interesting so I'll be checking it out further on a desktop browser.

**Comment by jkarni** [comment]
thanks for the bug report! I'll see if remarkJS is any better

**Comment by alpmestan** [comment]
Using another library for presentations is basically just about switching the pandoc command we use to generate it. If you have any recommendation I'd be glad to try and see if it's any better.

**Comment by bkaes** [comment]
Getting started is also impossible to view in FF and Opera for Android.

**Comment by alpmestan** [comment]
Is there any "slide-oriented" backend for pandoc that you folks would recommend that works well on mobile browsers? I will probably take the opportunity of having to update the getting started for the next release to generate it using another presentation library.

**Comment by bkaes** [comment]
Do you _really need slides_? There's not much missing to a full text document, which can be read regardless of the used device.

**Comment by jkarni** [comment]
I agree.

**Comment by alpmestan** [comment]
I liked the lightweight format that slides offer and we got a lot of good feedback about the getting started guide. It's produced with pandoc anyway so we can have a slideshow version and a good old html page (and even a PDF version?).

**Comment by alpmestan** [comment]
By the way, I'm currently rewriting the getting-started (and we've completely revamped the website too). It will be a good old HTML page integrated to the website. This should definitely improve the mobile experience :+1:

**Comment by alpmestan** [comment]
The getting started has been rewritten to become a more informative tutorial, available here: http://haskell-servant.github.io/tutorial

It's also now a good old HTML page, as mentionned above. Let me know if it's better. If it is, you can close this issue :)
