### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by algas** [haskell-servant/haskell-servant.github.io#50]
Could I publish Japanese translation of this document in my github pages in order to introduce servant to Japanese programmers? I would like to know the license and rules to publish translations if you have.

**Comment by soenkehahn** [comment]
Great that you want to do a translation!

I created #51 to add a license that allows what you want to do. Have to wait until all contributors agreed.

Note however that the servant tutorial moved into the main repo: https://github.com/haskell-servant/servant/tree/master/doc/tutorial

**Comment by algas** [comment]
@soenkehahn Thanks.

**Comment by algas** [comment]
#51 Thank you all.
