### ISSUE TITLE
Affiliation with the Haskell Foundation

### ISSUE THREAD

**Issue by tchoutri** [haskell-servant/haskell-servant.github.io#65]
Following the discussions that happened in the team I would like us to visibly vote in favour of our affiliation with the Haskell Foundation

This will cement Servant's place as a cornerstone of the ecosystem, as well as allow companies to make in-kind donations to the Foundation that can be directed to Servant.

@haskell-servant/maintainers let us vote. Please comment with your explicit approval.

**Comment by tchoutri** [comment]
I vote yes.

**Comment by arianvp** [comment]
Approved from my side

**Comment by akhesaCaro** [comment]
What does this affiliation apply?
What are the pros and cons?

**Comment by domenkozar** [comment]
👍

**Comment by alpmestan** [comment]
Approved as well.

**Comment by gdeest** [comment]
Just let me put some resources here:

> We invite existing Haskell projects, committees and communities to explicitly affiliate and align themselves with the Haskell Foundation. Affiliation means that the group supports the goals of the Haskell Foundation, and that the Haskell Foundation in turn supports this group.
> We require affiliated groups to adhere to guidelines around transparency, being open to new members, and follow the Haskell committee guidelines for respectful communication. We believe that this will help us grow towards being a more open and welcoming community.

https://haskell.foundation/affiliates/

The “Guidelines for Respectful Communication” are here:

https://haskell.foundation/guidelines-for-respectful-communication/

**Comment by jkarni** [comment]
:+1:

**Comment by akhesaCaro** [comment]
:+1:

**Comment by tchoutri** [comment]
Thanks everyone. :)
